langauge: ruby
sudo: false
cache: bundler

branches:
  only: master

rvm:
  - 2.3.7
  - 2.5.3

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

matrix:
  exclude:
  - rvm: 2.5.3
    gemfile: gemfiles/rails_3.gemfile

script:
  - 'psql -lqt | cut -d \| -f 1 | grep -qw modern_searchlogic-app-test || bundle exec appraisal rails-5 "cd spec/app_rails5/ && rake db:create"'
  - 'bundle exec appraisal rails-5 "cd spec/app_rails5/ && rake db:migrate db:test:prepare && rake db:environment:set RAILS_ENV=test"'
  - "bundle exec rspec"
bundler_args: ""
